### ISSUE TITLE
ML4T

### ISSUE THREAD

**Issue by ElenamaryD** [ankona/ml4t-docker#1]
Hi Chris,

So sorry to bother you, but if you have time and you can help I will really appreciate it.

I am a fellow ML4T classmate. I saw your posts on piazza and since I am completely lost on how to create/install the environment; I would like to ask you what do you mean install docker in your instructions, what environment do you use, and how you made things work, (being in the martingale directory and the grading & data folders along with util.py are in the root directory, etc.)

Thanks in advance.

**Comment by ankona** [comment]
I'd install "Docker Desktop" to run containers locally. The instructions can be found here: https://docs.docker.com/docker-for-mac/install/ or https://docs.docker.com/docker-for-windows/install/ for mac/windows.

Docker Desktop installs the container engine & CLI tools necessary to execute the build and run scripts (note: i'm a mac guy so paths in build/run.sh might be wrong for you if you're on windows. just execute them by hand in cmd.exe after cd'ing into your ML4T root directory).

The container serves as the 'environment' in this case so we don't have to worry about things like pyenv or anaconda. Python 3.6 is installed and the PYTHONPATH is configured to include the grader.py & util.py packages already.  

Once docker is installed, this example shows everything left:

![image](https://user-images.githubusercontent.com/3595025/72113425-68db9080-330e-11ea-8e68-8a741e6f3ba7.png)

And here are the commands from the screenshot:

- mkdir tmp
- cd tmp
- git clone https://github.com/ankona/ml4t-docker.git
- cd ml4t-docker
- curl http://quantsoftware.gatech.edu/images/c/ce/ML4T_2020Spring.zip --output ML4T_2020Spring.zip
- curl http://quantsoftware.gatech.edu/images/9/92/20Spring_martingale.zip --output 20Spring_martingale.zip
- unzip -q ML4T_2020Spring.zip -d ML4T_2020Spring
- unzip -q 20Spring_martingale.zip -d ML4T_2020Spring
- sh build.sh
- &#35; edit run.sh now to have your path.
- sh run.sh

The container mounts your local ML4T_2020Spring folder so you can edit code locally or do a remote debug session using a plugin in VS Code. Any changes you make are saved and shared between the host and container.

**Comment by ElenamaryD** [comment]
Thank you so much I appreciate it.
